from pageobject.base import BasePage
from selenium.webdriver.common.by import By
import time
class HomePage(BasePage):
    home_page_input_username=(By.NAME,'username')
    home_page_button_password=(By.NAME,'password')
    home_page_button_denglu=(By.CSS_SELECTOR,'.fastlg_l button')
    home_page_button_moren=(By.CSS_SELECTOR, 'td h2 a')
    home_page_button_delete_choose=(By.CSS_SELECTOR,'tbody:nth-last-child(2) tr td:nth-child(2) input')
    home_page_button_delete=(By.LINK_TEXT,"删除")
    home_page_button_management=(By.LINK_TEXT,"管理中心")
    home_page_input_password=(By.NAME,"admin_password")
    home_page_button_submit01=(By.NAME,"submit")
    home_page_button_luntan=(By.LINK_TEXT, "论坛")
    iframe=(By.TAG_NAME,"iframe")
    home_page_button_add=(By.XPATH,'//*[@id="cpform"]/table/tbody[3]/tr/td[2]/div/a')
    home_page_button_sector_submit=(By.CSS_SELECTOR,"#submit_editsubmit")
    home_page_button_SectorManagement_quit=(By.CSS_SELECTOR,".uinfo a:nth-child(2)")
    home_page_button_quit=(By.LINK_TEXT,"退出")
    home_page_button_new=(By.CSS_SELECTOR,'tbody tr:nth-child(2)  td:nth-child(2) a')
    home_page_input_title = (By.NAME, 'subject')
    home_page_input_zhengwen = (By.NAME, 'message')
    home_page_button_submit = (By.NAME, "topicsubmit")
    home_page_button_reply = (By.ID,"post_reply")
    home_page_input_reply_text = (By.NAME, "message")
    home_page_button_replay_submit = (By.NAME, "replysubmit")

    def denglu(self,content1,content2):
        self.sendkeys(content1,*self.home_page_input_username)
        self.sendkeys(content2,*self.home_page_button_password)
        self.click(*self.home_page_button_denglu)
        time.sleep(5)
        self.click(*self.home_page_button_moren)
    def Delete(self):
        time.sleep(5)
        self.click(*self.home_page_button_delete_choose)
        time.sleep(3)
        self.click(*self.home_page_button_delete)
        time.sleep(3)
    def SectorManagement(self,content):
        time.sleep(5)
        self.click(*self.home_page_button_management)
        time.sleep(7)
        self.driver.switch_to.window(self.driver.window_handles[1])
        time.sleep(5)
        try:
            self.sendkeys(content, *self.home_page_input_password)
            time.sleep(3)
            self.click(*self.home_page_button_submit01)
            time.sleep(3)
        except:
            pass
        time.sleep(3)
        self.click(*self.home_page_button_luntan)
        time.sleep(5)
        self.frame(*self.iframe)
        time.sleep(3)
        self.click(*self.home_page_button_add)
        time.sleep(3)
        self.click(*self.home_page_button_sector_submit)
        time.sleep(5)
        self.driver.switch_to.window(self.driver.window_handles[1])
        self.click(*self.home_page_button_SectorManagement_quit)
        self.driver.switch_to.window(self.driver.window_handles[1])
    def quit(self):
        self.click(*self.home_page_button_quit)
        time.sleep(3)
    def AverageUser(self,content1,content2):
        time.sleep(3)
        self.sendkeys(content1, *self.home_page_input_username)
        self.sendkeys(content2, *self.home_page_button_password)
        self.click(*self.home_page_button_denglu)
        time.sleep(3)
    def FaTie(self,content1,content2):
        self.click(*self.home_page_button_new)
        time.sleep(3)
        self.sendkeys(content1,*self.home_page_input_title)
        time.sleep(3)
        self.sendkeys(content2,*self.home_page_input_zhengwen)
        time.sleep(3)
        self.click(*self.home_page_button_submit)
        time.sleep(3)
    def HuiTie(self,content):
        time.sleep(3)
        self.click(*self.home_page_button_reply)
        time.sleep(3)
        self.sendkeys(content,*self.home_page_input_reply_text)
        time.sleep(3)
        self.click(*self.home_page_button_replay_submit)

